### ISSUE TITLE
How to handle inputs that are arrays

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/ParamTools#77]
I'm trying to convert the OG-USA `default_parameters.json` into a format that works with ParamTools.  

When I try to create an instances of the `Parameters` class with a converted version of the `default_parameters.json`, I get an error if I set `array_first = True`:

```
  File "/Users/jason.debacker/repos/ParamTools/paramtools/parameters.py", line 407, in to_array
    arr[ix] = vi["value"]
ValueError: setting an array element with a sequence.
```

If I set `array_first = False`, I am able to create an instance of the `Parameters` class, but I don't get the expected output.  E.g.

```
print("Frisch elasticity w paramtools 0.6.0")
print("\tas array", params.frisch)
print("\tas dict", params.from_array("frisch"))
```

Yields:

```
Frisch elasticity w paramtools 0.6.0
	as array [{'value': 0.4}]
Traceback (most recent call last):
  File "convert.py", line 95, in <module>
    print("\tas dict", params.from_array("frisch"))
  File "/Users/jason.debacker/repos/ParamTools/paramtools/parameters.py", line 425, in from_array
    "A NumPy Ndarray should be passed to this method "
TypeError: A NumPy Ndarray should be passed to this method or the instance attribute should be an array.
```

My sense is that the second error has to do with the `array_first = False`.  And that the first error, seen when `array_first = True` maybe have to do with trying to set elements of an array with a list, which is how some vector and multidimensional arrays of parameters are specified as.  E.g., see the `eta` parameter [here](https://github.com/PSLmodels/OG-USA/blob/f33467f79e803415a05fa6ecd016cd6b99c7940a/ogusa/default_parameters.json#L658).

Any help on how I should deal with this issue would be appreciated.

**Comment by hdoupe** [comment]
@jdebacker which version of ParamTools are you using? PR #76 should have fixed the first bug. That fix is in ParamTools 0.10.1.

`from_array` expects a numpy array and returns a list of dicts. Since the value couldn't be turned into a numpy array, it just got the list of dicts which is why it threw an error.

**Comment by jdebacker** [comment]
@hdoupe 

I guess I'm not totally understanding what I need to add.  Do I need a `number_dims` for each array object?

E.g., the `eta` would be written as:

```
"eta": {
        "title": "Government transfer allocation",
        "description": "Matrix that allocated government transfers across households.",
        "notes": "This SxJ matrix gives the fraction of total aggregate transfers going to each age s and ability type j.",
        "type": "float",
        " number_dims": 2,
        "value": [
            {
                "value": [
                    [
                        0.00395156539,
                        0.00395156539,
                        0.00316125231,
                        0.00158062616,
                        0.00158062616,
                        0.00142256354,
                        0.000158062616
                    ],
                    [
                        0.00397057633,
                        0.00397057633,
                        0.00317646106,
                        0.00158823053,
                        0.00158823053,
                        0.00142940748,
                        0.000158823053
                    ],
                    [
                        0.00399140521,
                        0.00399140521,
                        0.00319312416,
                        0.00159656208,
                        0.00159656208,
                        0.00143690587,
                        0.000159656208
                    ],
                    [
                        0.00401335125,
                        0.00401335125,
                        0.003210681,
                        0.0016053405,
                        0.0016053405,
                        0.00144480645,
                        0.00016053405
                    ],
                    [
                        0.0040353396,
                        0.0040353396,
                        0.00322827168,
                        0.00161413584,
                        0.00161413584,
                        0.00145272226,
                        0.000161413584
                    ],
                    [
                        0.00405670193,
                        0.00405670193,
                        0.00324536154,
                        0.00162268077,
                        0.00162268077,
                        0.00146041269,
                        0.000162268077
                    ],
                    [
                        0.0040761153,
                        0.0040761153,
                        0.00326089224,
                        0.00163044612,
                        0.00163044612,
                        0.00146740151,
                        0.000163044612
                    ],
                    [
                        0.00409333545,
                        0.00409333545,
                        0.00327466836,
                        0.00163733418,
                        0.00163733418,
                        0.00147360076,
                        0.000163733418
                    ],
                    [
                        0.00410837135,
                        0.00410837135,
                        0.00328669708,
                        0.00164334854,
                        0.00164334854,
                        0.00147901369,
                        0.000164334854
                    ],
                    [
                        0.00412086399,
                        0.00412086399,
                        0.00329669119,
                        0.0016483456,
                        0.0016483456,
                        0.00148351104,
                        0.00016483456
                    ],
                    [
                        0.004130814,
                        0.004130814,
                        0.0033046512,
                        0.0016523256,
                        0.0016523256,
                        0.00148709304,
                        0.00016523256
                    ],
                    [
                        0.0041388937,
                        0.0041388937,
                        0.00331111496,
                        0.00165555748,
                        0.00165555748,
                        0.00149000173,
                        0.000165555748
                    ],
                    [
                        0.00414547736,
                        0.00414547736,
                        0.00331638188,
                        0.00165819094,
                        0.00165819094,
                        0.00149237185,
                        0.000165819094
                    ],
                    [
                        0.00415083838,
                        0.00415083838,
                        0.0033206707,
                        0.00166033535,
                        0.00166033535,
                        0.00149430182,
                        0.000166033535
                    ],
                    [
                        0.00415488494,
                        0.00415488494,
                        0.00332390795,
                        0.00166195398,
                        0.00166195398,
                        0.00149575858,
                        0.000166195398
                    ],
                    [
                        0.00415765147,
                        0.00415765147,
                        0.00332612118,
                        0.00166306059,
                        0.00166306059,
                        0.00149675453,
                        0.000166306059
                    ],
                    [
                        0.00415882813,
                        0.00415882813,
                        0.00332706251,
                        0.00166353125,
                        0.00166353125,
                        0.00149717813,
                        0.000166353125
                    ],
                    [
                        0.00415877597,
                        0.00415877597,
                        0.00332702078,
                        0.00166351039,
                        0.00166351039,
                        0.00149715935,
                        0.000166351039
                    ],
                    [
                        0.00415741548,
                        0.00415741548,
                        0.00332593239,
                        0.00166296619,
                        0.00166296619,
                        0.00149666957,
                        0.000166296619
                    ],
                    [
                        0.00415480168,
                        0.00415480168,
                        0.00332384134,
                        0.00166192067,
                        0.00166192067,
                        0.0014957286,
                        0.000166192067
                    ],
                    [
                        0.00415094623,
                        0.00415094623,
                        0.00332075698,
                        0.00166037849,
                        0.00166037849,
                        0.00149434064,
                        0.000166037849
                    ],
                    [
                        0.00414595663,
                        0.00414595663,
                        0.00331676531,
                        0.00165838265,
                        0.00165838265,
                        0.00149254439,
                        0.000165838265
                    ],
                    [
                        0.00413994913,
                        0.00413994913,
                        0.00331195931,
                        0.00165597965,
                        0.00165597965,
                        0.00149038169,
                        0.000165597965
                    ],
                    [
                        0.00413307009,
                        0.00413307009,
                        0.00330645607,
                        0.00165322804,
                        0.00165322804,
                        0.00148790523,
                        0.000165322804
                    ],
                    [
                        0.00412533994,
                        0.00412533994,
                        0.00330027195,
                        0.00165013598,
                        0.00165013598,
                        0.00148512238,
                        0.000165013598
                    ],
                    [
                        0.00411571867,
                        0.00411571867,
                        0.00329257494,
                        0.00164628747,
                        0.00164628747,
                        0.00148165872,
                        0.000164628747
                    ],
                    [
                        0.00410463912,
                        0.00410463912,
                        0.00328371129,
                        0.00164185565,
                        0.00164185565,
                        0.00147767008,
                        0.000164185565
                    ],
                    [
                        0.0040923822,
                        0.0040923822,
                        0.00327390576,
                        0.00163695288,
                        0.00163695288,
                        0.00147325759,
                        0.000163695288
                    ],
                    [
                        0.00407842935,
                        0.00407842935,
                        0.00326274348,
                        0.00163137174,
                        0.00163137174,
                        0.00146823457,
                        0.000163137174
                    ],
                    [
                        0.00406247076,
                        0.00406247076,
                        0.00324997661,
                        0.0016249883,
                        0.0016249883,
                        0.00146248947,
                        0.00016249883
                    ],
                    [
                        0.00404485785,
                        0.00404485785,
                        0.00323588628,
                        0.00161794314,
                        0.00161794314,
                        0.00145614883,
                        0.000161794314
                    ],
                    [
                        0.00402617428,
                        0.00402617428,
                        0.00322093943,
                        0.00161046971,
                        0.00161046971,
                        0.00144942274,
                        0.000161046971
                    ],
                    [
                        0.00400535937,
                        0.00400535937,
                        0.0032042875,
                        0.00160214375,
                        0.00160214375,
                        0.00144192937,
                        0.000160214375
                    ],
                    [
                        0.00398258969,
                        0.00398258969,
                        0.00318607175,
                        0.00159303588,
                        0.00159303588,
                        0.00143373229,
                        0.000159303588
                    ],
                    [
                        0.00395814392,
                        0.00395814392,
                        0.00316651514,
                        0.00158325757,
                        0.00158325757,
                        0.00142493181,
                        0.000158325757
                    ],
                    [
                        0.00393179647,
                        0.00393179647,
                        0.00314543717,
                        0.00157271859,
                        0.00157271859,
                        0.00141544673,
                        0.000157271859
                    ],
                    [
                        0.00390383957,
                        0.00390383957,
                        0.00312307165,
                        0.00156153583,
                        0.00156153583,
                        0.00140538224,
                        0.000156153583
                    ],
                    [
                        0.00387400035,
                        0.00387400035,
                        0.00309920028,
                        0.00154960014,
                        0.00154960014,
                        0.00139464013,
                        0.000154960014
                    ],
                    [
                        0.00384196877,
                        0.00384196877,
                        0.00307357502,
                        0.00153678751,
                        0.00153678751,
                        0.00138310876,
                        0.000153678751
                    ],
                    [
                        0.00380787789,
                        0.00380787789,
                        0.00304630231,
                        0.00152315115,
                        0.00152315115,
                        0.00137083604,
                        0.000152315115
                    ],
                    [
                        0.00377185201,
                        0.00377185201,
                        0.00301748161,
                        0.0015087408,
                        0.0015087408,
                        0.00135786672,
                        0.00015087408
                    ],
                    [
                        0.0037340474,
                        0.0037340474,
                        0.00298723792,
                        0.00149361896,
                        0.00149361896,
                        0.00134425707,
                        0.000149361896
                    ],
                    [
                        0.00369312767,
                        0.00369312767,
                        0.00295450213,
                        0.00147725107,
                        0.00147725107,
                        0.00132952596,
                        0.000147725107
                    ],
                    [
                        0.00364931125,
                        0.00364931125,
                        0.002919449,
                        0.0014597245,
                        0.0014597245,
                        0.00131375205,
                        0.00014597245
                    ],
                    [
                        0.00360766197,
                        0.00360766197,
                        0.00288612958,
                        0.00144306479,
                        0.00144306479,
                        0.00129875831,
                        0.000144306479
                    ],
                    [
                        0.00356285967,
                        0.00356285967,
                        0.00285028773,
                        0.00142514387,
                        0.00142514387,
                        0.00128262948,
                        0.000142514387
                    ],
                    [
                        0.00351155021,
                        0.00351155021,
                        0.00280924016,
                        0.00140462008,
                        0.00140462008,
                        0.00126415807,
                        0.000140462008
                    ],
                    [
                        0.00345670257,
                        0.00345670257,
                        0.00276536205,
                        0.00138268103,
                        0.00138268103,
                        0.00124441292,
                        0.000138268103
                    ],
                    [
                        0.00340163241,
                        0.00340163241,
                        0.00272130593,
                        0.00136065297,
                        0.00136065297,
                        0.00122458767,
                        0.000136065297
                    ],
                    [
                        0.00334480304,
                        0.00334480304,
                        0.00267584243,
                        0.00133792122,
                        0.00133792122,
                        0.00120412909,
                        0.000133792122
                    ],
                    [
                        0.00328292059,
                        0.00328292059,
                        0.00262633647,
                        0.00131316824,
                        0.00131316824,
                        0.00118185141,
                        0.000131316824
                    ],
                    [
                        0.00321650788,
                        0.00321650788,
                        0.00257320631,
                        0.00128660315,
                        0.00128660315,
                        0.00115794284,
                        0.000128660315
                    ],
                    [
                        0.00314624315,
                        0.00314624315,
                        0.00251699452,
                        0.00125849726,
                        0.00125849726,
                        0.00113264753,
                        0.000125849726
                    ],
                    [
                        0.00307157839,
                        0.00307157839,
                        0.00245726271,
                        0.00122863136,
                        0.00122863136,
                        0.00110576822,
                        0.000122863136
                    ],
                    [
                        0.00299199285,
                        0.00299199285,
                        0.00239359428,
                        0.00119679714,
                        0.00119679714,
                        0.00107711743,
                        0.000119679714
                    ],
                    [
                        0.00290744259,
                        0.00290744259,
                        0.00232595407,
                        0.00116297703,
                        0.00116297703,
                        0.00104667933,
                        0.000116297703
                    ],
                    [
                        0.00281749792,
                        0.00281749792,
                        0.00225399834,
                        0.00112699917,
                        0.00112699917,
                        0.00101429925,
                        0.000112699917
                    ],
                    [
                        0.00272138616,
                        0.00272138616,
                        0.00217710893,
                        0.00108855447,
                        0.00108855447,
                        0.000979699019,
                        0.000108855447
                    ],
                    [
                        0.00261938813,
                        0.00261938813,
                        0.00209551051,
                        0.00104775525,
                        0.00104775525,
                        0.000942979727,
                        0.000104775525
                    ],
                    [
                        0.00251105115,
                        0.00251105115,
                        0.00200884092,
                        0.00100442046,
                        0.00100442046,
                        0.000903978414,
                        0.000100442046
                    ],
                    [
                        0.00239617674,
                        0.00239617674,
                        0.00191694139,
                        0.000958470695,
                        0.000958470695,
                        0.000862623626,
                        9.58470695e-05
                    ],
                    [
                        0.00227487878,
                        0.00227487878,
                        0.00181990302,
                        0.000909951512,
                        0.000909951512,
                        0.000818956361,
                        9.09951512e-05
                    ],
                    [
                        0.00214701698,
                        0.00214701698,
                        0.00171761358,
                        0.000858806792,
                        0.000858806792,
                        0.000772926113,
                        8.58806792e-05
                    ],
                    [
                        0.00201259941,
                        0.00201259941,
                        0.00161007953,
                        0.000805039765,
                        0.000805039765,
                        0.000724535788,
                        8.05039765e-05
                    ],
                    [
                        0.00187184833,
                        0.00187184833,
                        0.00149747867,
                        0.000748739333,
                        0.000748739333,
                        0.000673865399,
                        7.48739333e-05
                    ],
                    [
                        0.00172541264,
                        0.00172541264,
                        0.00138033011,
                        0.000690165054,
                        0.000690165054,
                        0.000621148549,
                        6.90165054e-05
                    ],
                    [
                        0.00157491245,
                        0.00157491245,
                        0.00125992996,
                        0.000629964979,
                        0.000629964979,
                        0.000566968481,
                        6.29964979e-05
                    ],
                    [
                        0.00142220089,
                        0.00142220089,
                        0.00113776071,
                        0.000568880357,
                        0.000568880357,
                        0.000511992321,
                        5.68880357e-05
                    ],
                    [
                        0.00126948236,
                        0.00126948236,
                        0.00101558589,
                        0.000507792943,
                        0.000507792943,
                        0.000457013648,
                        5.07792943e-05
                    ],
                    [
                        0.00111831414,
                        0.00111831414,
                        0.000894651316,
                        0.000447325658,
                        0.000447325658,
                        0.000402593092,
                        4.47325658e-05
                    ],
                    [
                        0.000971364381,
                        0.000971364381,
                        0.000777091505,
                        0.000388545752,
                        0.000388545752,
                        0.000349691177,
                        3.88545752e-05
                    ],
                    [
                        0.000830982831,
                        0.000830982831,
                        0.000664786265,
                        0.000332393132,
                        0.000332393132,
                        0.000299153819,
                        3.32393132e-05
                    ],
                    [
                        0.000699517695,
                        0.000699517695,
                        0.000559614156,
                        0.000279807078,
                        0.000279807078,
                        0.00025182637,
                        2.79807078e-05
                    ],
                    [
                        0.00057872894,
                        0.00057872894,
                        0.000462983152,
                        0.000231491576,
                        0.000231491576,
                        0.000208342418,
                        2.31491576e-05
                    ],
                    [
                        0.000469422939,
                        0.000469422939,
                        0.000375538351,
                        0.000187769176,
                        0.000187769176,
                        0.000168992258,
                        1.87769176e-05
                    ],
                    [
                        0.000373067125,
                        0.000373067125,
                        0.0002984537,
                        0.00014922685,
                        0.00014922685,
                        0.000134304165,
                        1.4922685e-05
                    ],
                    [
                        0.000290043322,
                        0.000290043322,
                        0.000232034658,
                        0.000116017329,
                        0.000116017329,
                        0.000104415596,
                        1.16017329e-05
                    ],
                    [
                        0.000220585214,
                        0.000220585214,
                        0.000176468171,
                        8.82340856e-05,
                        8.82340856e-05,
                        7.9410677e-05,
                        8.82340856e-06
                    ],
                    [
                        0.000163827444,
                        0.000163827444,
                        0.000131061955,
                        6.55309777e-05,
                        6.55309777e-05,
                        5.89778799e-05,
                        6.55309777e-06
                    ],
                    [
                        0.000118543187,
                        0.000118543187,
                        9.48345498e-05,
                        4.74172749e-05,
                        4.74172749e-05,
                        4.26755474e-05,
                        4.74172749e-06
                    ]
                ]
            }
        ],
        "validators": {
            "range": {
                "min": 0.0,
                "max": 1.0
            }
        }
```

**Comment by jdebacker** [comment]
@hdoupe Got it - adding `number_dims` seemed to work.  Thanks for the help.

FYI - I was installing ParamTools from source.  I don't know if I'm having general conda-forge issues or if it is something with the ParamTools package, but I cannot get it to install from conda.

**Comment by hdoupe** [comment]
@jdebacker I'm glad you got it figured out! `number_dims` needs to be specified if the value is an array. If not specified, ParamTools assumes the value is a scalar or sting.

I haven't run into any issues installing with conda. I think @Peter-Metz has been able to install using conda without any problems, too.
